# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb4c75c2f22112a58e71eccee7ca978e54005e4d3eb9bd3bfffaf847eadde64d610a06d3593727c90fa326f8a306eb8991a1736c7c941eb5c8ceda514045ffb8

test:
  secret_key_base: 22eed4b975f6c1ead454905f60eca9281b0a1ffcef831dcd5f672f201cc527be42b580e24366976f0b22dafdf63c7923da2b8df97041c3134b6d0e5c2e10c333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
